name: Check Pull Request

on:
  pull_request:
    paths:
      - '**/App.js'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for ASDF in App.js
      run: |
        if grep -q "ASDF" src/App.js; then
          echo "Error: ASDF found in src/App.js. Please remove it before merging."
          exit 1
        fi

    - name: Check for SEARCH_PATTERN in App.js
      run: |
        SEARCH_PATTERN=${{ secrets.SEARCH_PATTERN }}
        
    - name: Check for pattern in App.js
      run: |
        if grep -q "$SEARCH_PATTERN" src/App.js; then
          echo "Error: '$SEARCH_PATTERN' found in src/App.js. Please remove it before merging."
          exit 1
        fi
