name: Protect against secret leaks

on:
  pull_request:
    paths:
      - '**/App.js'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch pattern from secrets
      run: |
        SEARCH_PATTERN=${{ secrets.SEARCH_PATTERN }}
        
    - name: Check for pattern in App.js
      run: |
        echo "Looking for $SEARCH_PATTERN"
        echo $SEARCH_PATTERN |wc 
        if grep -q "$SEARCH_PATTERN" src/App.js; then
          echo "Error: '$SEARCH_PATTERN' found in src/App.js. Please remove it before merging."
          exit 1
        fi
